image: python:3.4
services:
  - postgres

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: zoe
  POSTGRES_USER: zoeuser
  POSTGRES_PASSWORD: zoepass

static_test:
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_tests.txt
    - chmod 755 run_tests.sh && ./run_tests.sh

SonarQube:
  image: sonar-scanner
  variables:
    SONAR_PROJECT_KEY: "zoe.public.eurecom"
    SONAR_PROJECT_NAME: "$CI_PROJECT_NAME"
    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
    SONARQUBE_SERVER_URL: "$SONARQUBE_SERVER_URL"
  script:
    - /usr/bin/sonar-scanner-run.sh
