inherits:
  - strictness_veryhigh

ignore:
  - (^|/)\..+
  - ^docs/
  - ^build/

uses:
  - flask

member-warning: true

output-format: grouped

dodgy:
    # Looks at Python code to search for things which look "dodgy"
    # such as passwords or git conflict artifacts
    run: true

mccabe:
    # complexity checking.
    run: true

pep257:
    # docstring checking
    run: true

pep8:
    # style checking
    run: false

pyflakes:
    # preferring 'frosted' instead (a fork of)
    run: true

pylint:
    # static analysis and then some, see .pylintrc file for configuration
    run: true

pyroma:
    # checks setup.py
    run: false

vulture:
    # this tool does a good job of finding unused code.
    run: true
