language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install pytest
before_script:
  - bash tests/resources/create_db.sh
script:
  - PYTHONPATH=. py.test --test-environment travis --cov=zoe_scheduler --cov=zoe_client --cov=zoe_web
  - sphinx-build -nW -b html -d docs/_build/doctrees docs/ docs/_build/html
