language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
before_script:
script:
  - PYTHONPATH=. py.test --cov=zoe_cmd --cov=zoe_lib --cov=zoe_master --cov=zoe_observer --cov=zoe_web
