language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
before_script:
script:
  - pylint *.py zoe_*
  - mypy -s *.py zoe_*
  - doc8 docs/
