language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install pytest
before_script:
  - cp .travis/zoe.conf .
  - bash .travis/create_db.sh
script:
  - py.test
  - sphinx-build -nW -b html -d docs/_build/doctrees docs/ docs/_build/html
