version: '2'
services:
  postgres:
    image: postgres:9.3
  zoe-api:
    image: zoerepo/zoe-test
    command: python3 zoe-api.py --debug --backend DockerEngine --backend-docker-config-file /etc/zoe/docker.conf --deployment-name compose --master-url tcp://zoe-master:4850 --dbuser postgres --dbhost postgres --dbname postgres
    ports:
      - "8080:5001"
    depends_on:
      - postgres
  zoe-master:
    image: zoerepo/zoe-test
    ports:
      - "4850:4850"
    volumes:
      - /etc/zoe:/etc/zoe
      - /opt/zoe-workspaces:/mnt/zoe-workspaces
    command: python3 zoe-master.py --debug --backend DockerEngine --backend-docker-config-file /etc/zoe/docker.conf --deployment-name compose --dbuser postgres --dbhost postgres --dbname postgres
    depends_on:
      - zoe-api
networks:
  zoe:
    driver: bridge
